version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379    
  app:
    links:
      - redis  
    build: .
    command: 
      sh -c 'redis-server & yarn dev'
    volumes:
      - .:/app:cached
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - redis